/**:
    ros__parameters:
        en_test: true
        en_instaRes: false # 是否启用兑换复活
        en_gimbal_spin: true   
        en_chassis_spin: true 
        hp_threshold: 200
        en_chase_enemy: false
        tracking_scope: 5.0
        gimbal_angular_vel: 1.2
        chassis_angular_vel: 6
        home_pose:  # 原地
            x: 0.0
            y: 0.0
            yaw: 0.0
        supply_zone_pose:
            x: 0.0
            y: 0.0
            yaw: 0.0