/**:
    ros__parameters:
        #goal_pose:
        enemy_bunker_pose:
            x: -2.6
            y: 0.44
            yaw: 3.14
        enemy_startup_pose:
            x: 2.26
            y: 1.38
            yaw: 3.14
        our_bunker_pose:
            x: -0.16
            y: -0.35
            yaw: 3.14
        patrol_1:
            x: 4.06
            y: -0.26
            yaw: 3.14
        patrol_2:
            x: 3.5
            y: -2.3
            yaw: 3.14
        patrol_3:
            x: -0.1
            y: -2.3
            yaw: 3.14

        #condition:
        lowest_HP: 100 # 最低允许血量
        tuoluo_angular_vel: 0.7 # 小陀螺状态角速度
        gimbal_angular_vel: 0.8 # 云台搜敌时的角速度
        strategy: -1 # -1:未设置 0：游走 1：去对面哨兵启动区 2：去对面场地掩体 3：去我方场地掩体
        
