# 补给区
born_pose:
  pose:
    position:
      x: 1.0
      y: 0.5
      z: 0.0
    orientation:
      roll:  0
      pitch: 0
      yaw:   -3.14

# 出生点
supply_pose:
  pose:
    position:
      x: -1.0
      y: 0.5
      z: 0
    orientation:
      roll:  0
      pitch: 0
      yaw:   3.14

# 巡逻点 (可能有多个)
patrol_pose:
  pose:
    position:
      x: 7
      y: 5
      z: 0
    orientation:
      roll:  0
      pitch: 0
      yaw:   3.14