/**:
    ros__parameters:
        #goal_pose:
        enemy_door:
            x: 0.0
            y: 0.0
            z: 0.0
            yaw: 3.14
        enemy_outpost:
            x: 0.0
            y: 0.0
            z: 0.0
            yaw: 3.14
        enemy_keystone_heights:
            x: 0.0
            y: 0.0
            z: 0.0
            yaw: 3.14
        our_outpost:
            x: 0.0
            y: 0.0
            z: 0.0
            yaw: 3.14
        our_keystone_heights:
            x: 0.0
            y: 0.0
            z: 0.0
            yaw: 3.14
        #decision
        lowest_HP: 100 # 最低允许血量
        tuoluo_angular_vel: 0.7 # 小陀螺状态角速度
        openstage_strategy: -1 # -1：未设置  0：到对面家堵门 1：到对面家打人 2：打对面前哨站
                                        #   3：守自家前哨站 4：呆在自家巡逻区

